name:                robot


extra-source-files:
- README.md
- PREPARE.md

# Metadata used when publishing your package
synopsis:            Telegram demo bot for LambdaConf 2018 workshop.
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fizruk/lambdaconf-2018-workshop#readme>

dependencies:
- filepath
- random
- base
- aeson
- http-api-data
- http-client
- http-client-tls
- mtl
- servant-client
- telegram-bot-simple
- text
- time

ghc-options:
- -Wall

executables:
  demo-bot:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N # -N option provides concurrent running on all available cores.
